// <auto-generated />
using System;
using LibraryApp.Database.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Database.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260509131405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LibraryApp.Database.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            IsAvailable = true,
                            Isbn = "978-0132350884",
                            Owner = "Alice",
                            PublishedDate = new DateOnly(2008, 8, 1),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Thomas",
                            IsAvailable = false,
                            Isbn = "978-0135957059",
                            Owner = "Bob",
                            PublishedDate = new DateOnly(2019, 9, 23),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gang of Four",
                            IsAvailable = true,
                            Isbn = "978-0201633610",
                            Owner = "Alice",
                            PublishedDate = new DateOnly(1994, 10, 31),
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Fowler",
                            IsAvailable = true,
                            Isbn = "978-0134757599",
                            Owner = "Carol",
                            PublishedDate = new DateOnly(2018, 11, 20),
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eric Evans",
                            IsAvailable = false,
                            Isbn = "978-0321125217",
                            Owner = "Bob",
                            PublishedDate = new DateOnly(2003, 8, 22),
                            Title = "Domain-Driven Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
